// LED config
#define WS2812_DI_PIN GP15

#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BAND_PINWHEEL_SAT

// #define RGB_MATRIX_SLEEP // TODO: Enable this
// #define RGB_TRIGGER_ON_KEYDOWN // TODO: Should I enable this?
